# Flujo de trabajo para desplegar contenido estático en GitHub Pages
name: Desplegar contenido estático en Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Instalar dependencias
        run: npm ci
      - name: Construir
        run: npm run build
      - name: Configurar Pages
        uses: actions/configure-pages@v5
      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
